
version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9090:9090'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    ports:
      - '27017:27017'